#spring.profiles.active=dev
server.port=8081

spring.datasource.url=jdbc:postgresql://10.153.45.169:5432/gst_db
spring.datasource.username=gst_admin
spring.datasource.password=stage123

logging.level.root=DEBUG
logging.level.com.example=DEBUG
