#spring.profiles.active=dev
server.port=8081

spring.datasource.url=jdbc:postgresql://10.153.36.161:5432/ctdlocal
spring.datasource.username=postgres
spring.datasource.password=post123

cors.allowed-origins=http://localhost:3000,http://localhost:5173

logging.level.root=info
logging.level.com.example=info
